name: "IndexNow"
on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 0,12 * * *'

jobs:
  check-and-submit:
    runs-on: ubuntu-latest
    steps:
      - name: submit-to-bing
        uses: bojieyang/indexnow-action@v1
        with:
          sitemap-location: "https://yakumo.tw/sitemap.xml"  # change it
          endpoint: "www.bing.com"
          since: 1
          # minite, hour, day, week, month, year
          since-unit: "day"
          limit: 100
          key: ${{ secrets.INDEXNOW_KEY }}
          key-location: ${{ secrets.INDEXNOW_KEY_LOCATION }}
